from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, EmailStr

# ==========================================
# USER SCHEMAS
# ==========================================

class UserBase(BaseModel):
    user_name: str = Field(min_length=3, max_length=50)
    email: EmailStr # EmailStr automatically validates that it's a real email format!

class UserCreate(UserBase):
    pass

class UserResponse(UserBase):
    model_config = ConfigDict(from_attributes=True)
    
    # Generated by the database, so it only appears in the response
    id: int
    image_file: str | None = None

# ==========================================
# HABIT (PARTY) SCHEMAS
# ==========================================

class HabitBase(BaseModel):
    name: str = Field(min_length=1, max_length=50)
    description: str | None = Field(default=None, max_length=100)
    
    # The new Bitmask schedule replacing frequency/goal
    schedule_mask: int 
    
    # The explicit timeline for the tiny experiment
    start_date: datetime
    end_date: datetime | None = None
    
class HabitCreate(HabitBase):
    # Everything needed to create a habit is already in HabitBase
    pass

class HabitResponse(HabitBase):
    model_config = ConfigDict(from_attributes=True)
    
    id: int
    creator_id: int